/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserMusicListeningService } from "../userMusicListening.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserMusicListeningCreateInput } from "./UserMusicListeningCreateInput";
import { UserMusicListening } from "./UserMusicListening";
import { UserMusicListeningFindManyArgs } from "./UserMusicListeningFindManyArgs";
import { UserMusicListeningWhereUniqueInput } from "./UserMusicListeningWhereUniqueInput";
import { UserMusicListeningUpdateInput } from "./UserMusicListeningUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserMusicListeningControllerBase {
  constructor(
    protected readonly service: UserMusicListeningService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserMusicListening })
  @nestAccessControl.UseRoles({
    resource: "UserMusicListening",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUserMusicListening(
    @common.Body() data: UserMusicListeningCreateInput
  ): Promise<UserMusicListening> {
    return await this.service.createUserMusicListening({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,

        musicTrack: data.musicTrack
          ? {
              connect: data.musicTrack,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isListening: true,
        timestamp: true,

        user: {
          select: {
            id: true,
          },
        },

        musicTrack: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserMusicListening] })
  @ApiNestedQuery(UserMusicListeningFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserMusicListening",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userMusicListenings(
    @common.Req() request: Request
  ): Promise<UserMusicListening[]> {
    const args = plainToClass(UserMusicListeningFindManyArgs, request.query);
    return this.service.userMusicListenings({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isListening: true,
        timestamp: true,

        user: {
          select: {
            id: true,
          },
        },

        musicTrack: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserMusicListening })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserMusicListening",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userMusicListening(
    @common.Param() params: UserMusicListeningWhereUniqueInput
  ): Promise<UserMusicListening | null> {
    const result = await this.service.userMusicListening({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isListening: true,
        timestamp: true,

        user: {
          select: {
            id: true,
          },
        },

        musicTrack: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserMusicListening })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserMusicListening",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUserMusicListening(
    @common.Param() params: UserMusicListeningWhereUniqueInput,
    @common.Body() data: UserMusicListeningUpdateInput
  ): Promise<UserMusicListening | null> {
    try {
      return await this.service.updateUserMusicListening({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,

          musicTrack: data.musicTrack
            ? {
                connect: data.musicTrack,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          isListening: true,
          timestamp: true,

          user: {
            select: {
              id: true,
            },
          },

          musicTrack: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserMusicListening })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserMusicListening",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserMusicListening(
    @common.Param() params: UserMusicListeningWhereUniqueInput
  ): Promise<UserMusicListening | null> {
    try {
      return await this.service.deleteUserMusicListening({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          isListening: true,
          timestamp: true,

          user: {
            select: {
              id: true,
            },
          },

          musicTrack: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
