/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MusicTrackService } from "../musicTrack.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MusicTrackCreateInput } from "./MusicTrackCreateInput";
import { MusicTrack } from "./MusicTrack";
import { MusicTrackFindManyArgs } from "./MusicTrackFindManyArgs";
import { MusicTrackWhereUniqueInput } from "./MusicTrackWhereUniqueInput";
import { MusicTrackUpdateInput } from "./MusicTrackUpdateInput";
import { UserMusicListeningFindManyArgs } from "../../userMusicListening/base/UserMusicListeningFindManyArgs";
import { UserMusicListening } from "../../userMusicListening/base/UserMusicListening";
import { UserMusicListeningWhereUniqueInput } from "../../userMusicListening/base/UserMusicListeningWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MusicTrackControllerBase {
  constructor(
    protected readonly service: MusicTrackService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MusicTrack })
  @nestAccessControl.UseRoles({
    resource: "MusicTrack",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMusicTrack(
    @common.Body() data: MusicTrackCreateInput
  ): Promise<MusicTrack> {
    return await this.service.createMusicTrack({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        artist: true,
        album: true,
        duration: true,
        spotifyUri: true,
        appleMusicUri: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MusicTrack] })
  @ApiNestedQuery(MusicTrackFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MusicTrack",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async musicTracks(@common.Req() request: Request): Promise<MusicTrack[]> {
    const args = plainToClass(MusicTrackFindManyArgs, request.query);
    return this.service.musicTracks({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        artist: true,
        album: true,
        duration: true,
        spotifyUri: true,
        appleMusicUri: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MusicTrack })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MusicTrack",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async musicTrack(
    @common.Param() params: MusicTrackWhereUniqueInput
  ): Promise<MusicTrack | null> {
    const result = await this.service.musicTrack({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        artist: true,
        album: true,
        duration: true,
        spotifyUri: true,
        appleMusicUri: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MusicTrack })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MusicTrack",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMusicTrack(
    @common.Param() params: MusicTrackWhereUniqueInput,
    @common.Body() data: MusicTrackUpdateInput
  ): Promise<MusicTrack | null> {
    try {
      return await this.service.updateMusicTrack({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          artist: true,
          album: true,
          duration: true,
          spotifyUri: true,
          appleMusicUri: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MusicTrack })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MusicTrack",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMusicTrack(
    @common.Param() params: MusicTrackWhereUniqueInput
  ): Promise<MusicTrack | null> {
    try {
      return await this.service.deleteMusicTrack({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          artist: true,
          album: true,
          duration: true,
          spotifyUri: true,
          appleMusicUri: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/userMusicListenings")
  @ApiNestedQuery(UserMusicListeningFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserMusicListening",
    action: "read",
    possession: "any",
  })
  async findUserMusicListenings(
    @common.Req() request: Request,
    @common.Param() params: MusicTrackWhereUniqueInput
  ): Promise<UserMusicListening[]> {
    const query = plainToClass(UserMusicListeningFindManyArgs, request.query);
    const results = await this.service.findUserMusicListenings(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isListening: true,
        timestamp: true,

        user: {
          select: {
            id: true,
          },
        },

        musicTrack: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/userMusicListenings")
  @nestAccessControl.UseRoles({
    resource: "MusicTrack",
    action: "update",
    possession: "any",
  })
  async connectUserMusicListenings(
    @common.Param() params: MusicTrackWhereUniqueInput,
    @common.Body() body: UserMusicListeningWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userMusicListenings: {
        connect: body,
      },
    };
    await this.service.updateMusicTrack({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/userMusicListenings")
  @nestAccessControl.UseRoles({
    resource: "MusicTrack",
    action: "update",
    possession: "any",
  })
  async updateUserMusicListenings(
    @common.Param() params: MusicTrackWhereUniqueInput,
    @common.Body() body: UserMusicListeningWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userMusicListenings: {
        set: body,
      },
    };
    await this.service.updateMusicTrack({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/userMusicListenings")
  @nestAccessControl.UseRoles({
    resource: "MusicTrack",
    action: "update",
    possession: "any",
  })
  async disconnectUserMusicListenings(
    @common.Param() params: MusicTrackWhereUniqueInput,
    @common.Body() body: UserMusicListeningWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userMusicListenings: {
        disconnect: body,
      },
    };
    await this.service.updateMusicTrack({
      where: params,
      data,
      select: { id: true },
    });
  }
}
